name: Hammer
options:
  bundleIdPrefix: com.lyft
targets:
  Hammer:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    sources: Sources/Hammer
    settings:
      ENABLE_TESTING_SEARCH_PATHS: true
    scheme:
      testTargets:
        - HammerTests
      coverageTargets: 
        - Hammer
      gatherCoverageData: true
  HammerTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources: Tests/HammerTests
    settings:
      DEVELOPMENT_TEAM: 'H1A2M3M4ER'
    dependencies:
      - target: Hammer
      - target: TestHost
  TestHost:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: TestHost
    settings:
      DEVELOPMENT_TEAM: 'H1A2M3M4ER'
